sudo: required
services:
    - docker
before_install:
    - docker build -t achyutpdl/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true achyutpdl/docker-react npm run test -- --coverage